server:
  port: 8080

spring:
  profiles:
    # that is our default profile
    active: prod
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: Converter
  main:
    banner-mode: "off"

jodconverter:
  local:
    enabled: true
    port-numbers: 2002
    working-dir: /tmp

logging:
  level:
    org.jodconverter: info
